flags: {}
packages:
  - '.'
  - location:
      git: https://github.com/agrafix/Spock-digestive.git
      commit: 4c85647427e21bbaefbf04c4bc315d4bdfabba0e
    extra-dep: true
extra-deps:
  - digestive-functors-0.8.2.0
  - digestive-bootstrap-0.1.0.1
  - digestive-functors-blaze-0.6.1.0
resolver: lts-8.12
system-ghc: true
